### ISSUE TITLE
on reconnect channel join parsing issue

### ISSUE THREAD

**Issue by therealromster** [prologic/charla#2]
I was in the channels "#Romster" and "#circuits"  and on rejoin I got joined to "#Romster,#circuits".

**Comment by therealromster** [comment]
on subsequent reconnects "Now talking on #Romster,#circuits,#circuits"

**Comment by prologic** [comment]
Interesting:

```
2015-08-24 19:11:40,401 - charla.plugin - INFO - I: [::ffff:202.168.100.149:60700] 'JOIN #Romster,#circuits,#circuits\r\nMODE #circuits\r\n'
```

I'll add support for comma separated channels in the `JOIN` command.
